FROM node:lts-slim as src
WORKDIR /app
COPY ./web/package.json ./package.json
RUN npm install --legacy-peer-deps
COPY ./web .

FROM src as dist
RUN npm run build

FROM nginx as prod
RUN mkdir /app
COPY --from=dist /app/dist /app
COPY ./web/nginx.conf /etc/nginx/nginx.conf