FROM node:lts-slim as src
RUN npm install -g pm2 autocannon
RUN apt-get update
RUN apt-get install wait-for-it -y
WORKDIR /app
COPY ./api/package.json ./
RUN npm install
COPY ./api .
RUN npm run build:clean

FROM src as dist
ENV NODE_ENV=production